# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v6.1.1
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod:
  - hosts:
      - ${HOST}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 16.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "15"
project_author: Dixmit
project_license: OPL-1.0
project_name: myproject-odoo
smtp_default_from: ""
smtp_relay_host: ""
